# Generated by Django 4.2.5 on 2023-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="num_floors",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="floor",
            name="num_appartments",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
