# Generated by Django 4.2.5 on 2023-09-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0002_building_num_floors_floor_num_appartments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="floor",
            old_name="num_appartments",
            new_name="num_apartments",
        ),
    ]
