# Generated by Django 4.2.5 on 2023-09-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0003_rename_num_appartments_floor_num_apartments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="apartment_expense",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_bathrooms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_bedrooms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
