# Generated by Django 4.2.5 on 2023-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0005_alter_apartment_cost_to_rent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="appartment_number",
            new_name="apartment_number",
        ),
    ]
