# Generated by Django 4.2.5 on 2023-09-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0006_rename_appartment_number_apartment_apartment_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floor",
            options={"ordering": ["floor_number"]},
        ),
    ]
