# Generated by Django 4.2.5 on 2023-09-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0007_alter_floor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"ordering": ["floor__floor_number", "apartment_number"]},
        ),
        migrations.AlterModelOptions(
            name="floor",
            options={},
        ),
    ]
