# Generated by Django 4.2.5 on 2023-09-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0010_alter_apartment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="location",
        ),
        migrations.AddField(
            model_name="building",
            name="city",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="country",
            field=models.CharField(default="USA", max_length=100),
        ),
        migrations.AddField(
            model_name="building",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
